# Тема “Вычисления с помощью Numpy”
### ЗАДАНИЕ 1

In [23]:
import numpy as np
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [24]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### ЗАДАНИЕ 2

In [25]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### ЗАДАНИЕ 3

In [49]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [53]:
(a_centered_sp)/(np.shape(a)[0] - 1)

2.0

### Задание 4

In [57]:
coveration = np.cov(np.transpose(a))
coveration[0, 1]

2.0